set_property SRC_FILE_INFO {cfile:C:/Xilinx/Fontys/projects/MO3proof/MO3proof.srcs/constrs_1/new/constr.xdc rfile:../../../MO3proof.srcs/constrs_1/new/constr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {echo_0}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {pulse_0}]
